"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import {Avatar,ErrorNotice,PlayHeader,playRequest,sportName,when} from "@/components/play-ui";
import {lifecycleCopy} from "@/lib/play-lifecycle";
export default function GameRoom(){const[id,setId]=useState(""),[data,setData]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[scoreA,setScoreA]=useState("0"),[scoreB,setScoreB]=useState("0"),[confirmed,setConfirmed]=useState(false),[copied,setCopied]=useState(false);
 useEffect(()=>{const p=new URLSearchParams(location.search);setId(p.get("gameId")||p.get("id")||"");},[]);
 const load=useCallback(async()=>{if(!id)return;try{const d=await playRequest(`/api/play/game-room?gameId=${encodeURIComponent(id)}`);setData(d);}catch(e){setError((e as Error).message);}},[id]);useEffect(()=>{void load();const t=setInterval(()=>{if(document.visibilityState==="visible")void load();},10000);return()=>clearInterval(t);},[load]);
 async function run(action:string,extra:Record<string,unknown>={}){setBusy(true);setError("");try{const d=await playRequest("/api/play/game-room",{action,gameId:id,...extra});setData(d);if(action==="confirm_result")setConfirmed(true);}catch(e){setError((e as Error).message);await load();}finally{setBusy(false);}}
 const g=data?.game,copy=lifecycleCopy[data?.lifecycle||"open"];
 return <main className="p-page"><PlayHeader title="GAME ROOM" back="/play/games"/><ErrorNotice error={error}/>{!data?<p role="status" className="p-muted">Ładowanie pokoju gry…</p>:<><div className="p-kicker">{sportName(g.sport)} · {g.format}</div><h1>{g.courtName}</h1><p className="p-muted">{when(g.startsAt)} · {g.courtDistrict}</p><div className="p-steps">{Object.entries(lifecycleCopy).map(([key,value])=><span className={key===data.lifecycle?"p-step active":"p-step"} key={key}>{value.label}</span>)}</div><section className="p-card"><div className="p-row"><span className="p-badge">{confirmed?"CONFIRMED → COMPLETED":copy.label}</span><b>{data.players.length}/{g.maxPlayers} graczy</b></div><h2>{copy.instruction}</h2>{data.canJoin&&<button className="p-btn wide" disabled={busy} onClick={()=>run("join_game")}>DOŁĄCZ DO GRY</button>}{data.me&&g.status==="open"&&<div className="p-actions">{data.isCreator&&data.players.length===g.maxPlayers&&!data.players.every((p:any)=>p.team)&&<button className="p-btn secondary" disabled={busy} onClick={()=>run("generate_teams")}>WYGENERUJ DRUŻYNY</button>}{data.me.team&&<button className="p-btn" disabled={busy} onClick={()=>run("set_game_ready",{ready:!data.me.readyAt})}>{data.me.readyAt?"GOTOWY ✓ · cofnij":"JESTEM GOTOWY"}</button>}{data.isCreator&&data.lifecycle==="ready"&&<button className="p-btn" disabled={busy} onClick={()=>run("start_game")}>START GAME →</button>}{!data.isCreator&&<button className="p-btn secondary" disabled={busy} onClick={()=>run("leave_game")}>Opuść grę</button>}</div>}{g.status==="awaiting_confirmation"&&<><div className="p-kicker" style={{marginTop:20}}>RESULT SUBMITTED</div><div className="p-score">{g.scoreA}<span className="p-muted">:</span>{g.scoreB}</div><p className="p-muted">Drużyna A : Drużyna B. Sprawdź wynik przed potwierdzeniem.</p>{data.canConfirm?<div className="p-actions"><button className="p-btn" disabled={busy} onClick={()=>run("confirm_result")}>POTWIERDZAM WYNIK</button><button className="p-btn secondary" disabled={busy} onClick={()=>run("dispute_result")}>Wynik się nie zgadza</button></div>:<p className="p-muted">Czekamy na potwierdzenie przeciwnej drużyny.</p>}</>}{g.status==="completed"&&<><div className="p-score">{g.scoreA}<span className="p-muted">:</span>{g.scoreB}</div>{data.myEloChange&&<div className="p-stat">{data.myEloChange.change>=0?"+":""}{data.myEloChange.change} ELO <span className="p-muted">→ {data.myEloChange.after}</span></div>}<p className="p-muted">ELO jest zapisane. Powtórne potwierdzenie nie naliczy punktów drugi raz.</p><div className="p-actions"><Link className="p-btn" href={`/play/map?sport=${g.sport}&filter=play`}>NEXT GAME →</Link><Link className="p-btn secondary" href={`/play/rankings?sport=${g.sport}`}>ZOBACZ RANKING</Link></div></>}</section>
 <div className="p-grid">{["A","B"].map(team=><section className="p-card" key={team}><div className="p-row"><h2>Drużyna {team}</h2><span className="p-muted">{data.teams[`average${team}`]} ELO średnio</span></div>{data.players.filter((p:any)=>p.team===team).map((p:any)=><Link className="p-item" key={p.userId} href={`/play/player?id=${p.userId}&sport=${g.sport}`}><Avatar nickname={p.nickname} url={p.avatarUrl}/><div><b>@{p.nickname}</b><div className="p-muted">{p.elo} ELO · {p.tier}</div></div>{p.readyAt&&<span className="p-badge">READY ✓</span>}</Link>)}{!data.players.some((p:any)=>p.team===team)&&<p className="p-muted">Drużyny będą ustawione po zebraniu pełnego składu.</p>}</section>)}</div>{data.players.some((p:any)=>!p.team)&&<section className="p-card"><h2>Dołączyli do gry</h2>{data.players.filter((p:any)=>!p.team).map((p:any)=><div className="p-item" key={p.userId}><Avatar nickname={p.nickname} url={p.avatarUrl}/><div><b>@{p.nickname}</b><div className="p-muted">{p.elo} ELO</div></div></div>)}</section>}
 {data.canSubmit&&<section className="p-card" style={{marginTop:16}}><h2>Wpisz końcowy wynik</h2><p className="p-muted">Potwierdzi go druga drużyna.</p><form onSubmit={e=>{e.preventDefault();void run("submit_result",{scoreA:Number(scoreA),scoreB:Number(scoreB)});}}><div className="p-score"><input aria-label="Wynik drużyny A" type="number" inputMode="numeric" min="0" max="99" value={scoreA} onChange={e=>setScoreA(e.target.value)} required/><span>:</span><input aria-label="Wynik drużyny B" type="number" inputMode="numeric" min="0" max="99" value={scoreB} onChange={e=>setScoreB(e.target.value)} required/></div><button className="p-btn wide" disabled={busy}>WYŚLIJ WYNIK →</button></form></section>}
 <div className="p-actions"><Link className="p-btn secondary" href={`/play/court?id=${g.courtId}&sport=${g.sport}`}>COURT ↗</Link><button className="p-btn secondary" onClick={async()=>{try{await navigator.clipboard.writeText(location.href);setCopied(true);}catch{setError("SERVICE_UNAVAILABLE");}}}>{copied?"Link skopiowany ✓":"ZAPROŚ · skopiuj link"}</button></div></>}</main>;
}
