"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import {Avatar,ErrorNotice,Sports,playRequest,when} from "@/components/play-ui";
export default function PlayPage(){
 const[sport,setSport]=useState("football"),[data,setData]=useState<any>(null),[live,setLive]=useState<any>(null),[ranks,setRanks]=useState<any>(null),[court,setCourt]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const[d,l,r]=await Promise.all([playRequest("/api/play"),playRequest(`/api/play/discovery?sport=${sport}`),playRequest(`/api/play/rankings?sport=${sport}`)]);setData(d);setLive(l);setRanks(r);const home=d.homeCourts.find((h:any)=>h.sport===sport);setCourt(home?await playRequest(`/api/play/court?id=${home.courtId}&sport=${sport}`):null);setError("");}catch(e){setError((e as Error).message);}},[sport]);
 useEffect(()=>{void load();const timer=setInterval(()=>{if(document.visibilityState==="visible")void load();},30000);return()=>clearInterval(timer);},[load]);
 async function ready(){setBusy(true);try{await playRequest("/api/play/discovery",{action:live.me.ready?"clear_ready":"set_ready",sport,courtId:court?.court.id,minutes:60});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const me=data?.sports.find((p:any)=>p.sport===sport),challenges=data?.challenges.filter((c:any)=>c.status==="pending")||[];
 return <main className="p-page"><header className="p-header"><b style={{fontSize:18}}>GAMEFIELDS <span style={{color:"#77ff55"}}>PLAY</span></b><Link className="p-back" href="/play/account">{data?`@${data.user.nickname}`:"Konto"} ↗</Link></header><Sports sport={sport} setSport={setSport}/><ErrorNotice error={error}/>
 <section className="p-hero"><div className="p-kicker">FIND IT. PLAY IT. RANK IT. CHANGE IT.</div><h1>Twoje miasto.<br/>Twoja gra.</h1><p className="p-muted">Znajdź ludzi i miejsce. Reszta zaczyna się na boisku.</p><Link className="p-btn wide" href={`/play/map?sport=${sport}&filter=play`}>ZNAJDŹ GRĘ →</Link></section>
 {!data&&!error&&<p role="status" className="p-muted">Ładowanie Twojej aktywności…</p>}
 <div className="p-grid"><section className="p-card"><div className="p-row"><h2>Live near you</h2><Link className="p-back" href={`/play/map?sport=${sport}`}>MAP ↗</Link></div><p className="p-muted">{data?.user.city||"Twoje miasto"} · lokalizacja jest dobrowolna</p><div className="p-stats"><div><b>{live?.courts.reduce((n:number,c:any)=>n+c.playersNow,0)||0}</b><span>na boiskach</span></div><div><b>{live?.readyPlayers.length||0}</b><span>READY NOW</span></div><div><b>{live?.openGames.length||0}</b><span>otwartych gier</span></div></div>
 <button className={live?.me.ready?"p-btn secondary wide":"p-btn wide"} disabled={busy||!live} onClick={ready}>{live?.me.ready?"READY aktywne · wyłącz":"READY TO PLAY · jestem dostępny"}</button>{live?.me.ready&&<p className="p-muted">Do {new Date(live.me.availableUntil).toLocaleTimeString("pl-PL",{hour:"2-digit",minute:"2-digit"})}{court?` · ${court.court.name}`:""}</p>}
 <div className="p-list">{data?.games.filter((g:any)=>g.sport===sport).slice(0,3).map((g:any)=><Link className="p-item" key={g.id} href={`/play/game?gameId=${g.id}`}><div><b>{g.courtName}</b><div className="p-muted">{g.format} · {when(g.startsAt)}</div></div><span className="p-badge">{g.playerCount}/{g.maxPlayers} →</span></Link>)}</div>{!live?.openGames.length&&<p className="p-muted">Pierwszy ruch należy do Ciebie. <Link href={`/play/games?create=1&sport=${sport}`}>Utwórz grę →</Link></p>}
 {live?.readyPlayers.filter((p:any)=>p.userId!==data?.user.id).slice(0,3).map((p:any)=><Link key={p.userId} className="p-item" href={`/play/challenge/new?playerId=${p.userId}&sport=${sport}`}><Avatar nickname={p.nickname} url={p.avatarUrl}/><div><b>@{p.nickname}</b><div className="p-muted">{p.elo} ELO · {p.tier}</div></div><span className="p-badge">CHALLENGE</span></Link>)}</section>
 <section className="p-card"><div className="p-kicker">YOUR HOME COURT</div>{court?<><h2>{court.court.name}</h2><p className="p-muted">{court.court.city} · {court.court.district}</p><div className="p-stats"><div><b>{court.livePlayers.length}</b><span>LIVE players</span></div><div><b>#{ranks?.myRanks.court||"—"}</b><span>Twoja pozycja</span></div><div><b>{court.homePlayers}</b><span>Home Players</span></div></div><p className="p-muted">Court King: <b>{court.courtKing?`@${court.courtKing.nickname}`:"Pierwszy mecz wyłoni lidera"}</b></p>{court.upcomingGames[0]&&<p className="p-muted">Kolejna gra: {when(court.upcomingGames[0].startsAt)}</p>}<Link className="p-btn secondary wide" href={`/play/court?id=${court.court.id}&sport=${sport}`}>PLAY HERE →</Link></>:<><h2>Znajdź swoje miejsce.</h2><p className="p-muted">Wybierz Home Court i buduj lokalny ranking.</p><Link className="p-btn secondary wide" href="/play/onboarding">WYBIERZ HOME COURT</Link></>}</section>
 <section className="p-card"><div className="p-row"><div className="p-kicker">YOUR RANK · {sport.toUpperCase()}</div><Link className="p-back" href={`/play/rankings?sport=${sport}`}>Ranking ↗</Link></div><div className="p-stat">{me?.elo??"—"} <span className="p-muted">ELO</span></div><p className="p-muted">{me?.tier} · {me?.games||0} rozegranych gier</p><div className="p-stats"><div><b>#{ranks?.myRanks.city||"—"}</b><span>{data?.user.city||"City"}</span></div><div><b>#{ranks?.myRanks.district||"—"}</b><span>{ranks?.district||"District"}</span></div><div><b>{ranks?.streak||0}</b><span>win streak</span></div></div></section>
 <section className="p-card"><div className="p-row"><h2>Challenges</h2><Link className="p-back" href="/play/players">Rzuć wyzwanie ↗</Link></div>{challenges.slice(0,3).map((c:any)=><Link className="p-item" key={c.id} href={`/play/challenge?id=${c.id}`}><div><b>{c.participants.filter((p:any)=>p.userId!==data.user.id).map((p:any)=>`@${p.nickname}`).join(" · ")}</b><div className="p-muted">{c.courtName} · {c.format}<br/>{when(c.startsAt)}</div></div><span className="p-badge">OPEN →</span></Link>)}{!challenges.length&&<p className="p-muted">Nie masz oczekujących wyzwań. Znajdź zawodnika i ustalcie najbliższą grę.</p>}</section></div>
 <section className="p-card"><div className="p-kicker">CHANGE IT.</div><h2>Twoje boisko może więcej.</h2><p className="p-muted">Zgłoś problem, poprzyj zmianę albo zaprojektuj nową wersję w Gamefields Builder.</p><div className="p-actions"><Link className="p-btn secondary" href="/play/map?filter=improve">IMPROVE THIS PLACE</Link><Link className="p-btn secondary" href="/play/courts/add">ADD A SPOT +</Link></div></section>
 </main>;
}
