import assert from 'node:assert/strict';
import {readFile,readdir,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {resolve,extname} from 'node:path';
import {createServer} from 'node:http';
import {chromium} from 'playwright';
const require=createRequire(import.meta.url),wranglerRequire=createRequire(require.resolve('wrangler/package.json'));
const {Miniflare}=await import(wranglerRequire.resolve('miniflare'));
const files=(await readdir('dist/server',{recursive:true})).filter(f=>/\.m?js$/.test(f));
const mf=new Miniflare({modules:['index.js',...files.filter(f=>f!=='index.js')].map(f=>({type:'ESModule',path:resolve('dist/server',f)})),modulesRoot:resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB']});
let browser,server;
try{
 const db=await mf.getD1Database('DB');for(const file of (await readdir('drizzle')).filter(f=>/^\d+.*\.sql$/.test(f)).sort())await db.exec((await readFile(`drizzle/${file}`,'utf8')).replace(/--[^\n]*\n/g,'\n').replace(/\n/g,' '));
 const mime={'.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json','.woff2':'font/woff2'};
 server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname,file=resolve('dist/client','.'+path),root=resolve('dist/client')+'/';if(file.startsWith(root)&&!path.startsWith('/api/')){try{const bytes=await readFile(file);res.setHeader('Content-Type',mime[extname(file)]||'application/octet-stream');res.end(bytes);return;}catch{}}
 const chunks=[];for await(const c of req)chunks.push(c);const response=await mf.dispatchFetch(`http://${req.headers.host}${req.url}`,{method:req.method,headers:req.headers,body:chunks.length?Buffer.concat(chunks):undefined});res.statusCode=response.status;for(const [k,v]of response.headers)if(k!=='set-cookie')res.setHeader(k,v);const cookies=response.headers.getSetCookie();if(cookies.length)res.setHeader('Set-Cookie',cookies);res.end(Buffer.from(await response.arrayBuffer()));}catch(e){res.statusCode=500;res.end(String(e));}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://localhost:${server.address().port}`;
 const jar=[];async function api(who,path,body){const r=await mf.dispatchFetch(base+path,{method:body?'POST':'GET',headers:{Origin:base,'Content-Type':'application/json',Cookie:jar[who]||''},body:body?JSON.stringify(body):undefined});const d=await r.json();assert.ok(r.ok,`${path}: ${JSON.stringify(d)}`);const cookie=r.headers.getSetCookie().find(c=>c.startsWith('gf_play_session='));if(cookie)jar[who]=cookie.split(';')[0];return d;}
 const password='Pilot-'+crypto.randomUUID();const a=await api(0,'/api/play/auth',{action:'register',email:'mobile-a@example.test',password}),b=await api(1,'/api/play/auth',{action:'register',email:'mobile-b@example.test',password});
 for(let i=0;i<2;i++){await api(i,'/api/play',{action:'set_home_court',courtId:'court_lazienkowski',sport:'football'});await api(i,'/api/play/discovery',{action:'set_ready',courtId:'court_lazienkowski',sport:'football'});}
 const startsAt=new Date(Date.now()+600000).toISOString(),game=await api(0,'/api/play',{action:'create_game',courtId:'court_lazienkowski',sport:'football',format:'1v1',startsAt});await api(1,'/api/play/game-room',{action:'join_game',gameId:game.gameId});
 const challenge=await api(0,'/api/play',{action:'create_challenge',courtId:'court_lazienkowski',sport:'football',format:'1v1',startsAt,invitedUserIds:[b.user.id]});
 const tournament=await api(0,'/api/play/tournaments',{action:'create',courtId:'court_lazienkowski',sport:'football',format:'1v1',startsAt,maxEntries:2});await api(1,'/api/play/tournaments',{action:'join',tournamentId:tournament.tournamentId});await api(0,'/api/play/tournaments',{action:'start',tournamentId:tournament.tournamentId});
 browser=await chromium.launch({headless:true});await mkdir('outputs/mobile',{recursive:true});
 const routes=[['home','/play'],['map','/play/map'],['games','/play/games?create=1'],['court','/play/court?id=court_lazienkowski'],['game',`/play/game?gameId=${game.gameId}`],['players','/play/players'],['profile',`/play/player?id=${a.user.id}`],['challenge',`/play/challenge?id=${challenge.challengeId}`],['challenge-new',`/play/challenge/new?playerId=${b.user.id}`],['rankings','/play/rankings'],['spot','/play/courts/add'],['tournament',`/play/tournaments?id=${tournament.tournamentId}`],['builder','/play/builder?source=play&court_id=court_lazienkowski&sport=football']];
 let checked=0;const errors=[];
 for(const [width,height]of [[375,812],[390,844],[430,932]]){const context=await browser.newContext({viewport:{width,height},isMobile:true,hasTouch:true});await context.addCookies([{name:'gf_play_session',value:jar[0].split('=')[1],url:base,httpOnly:true,secure:true,sameSite:'Lax'}]);const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 for(const [name,path]of routes){await page.goto(base+path,{waitUntil:'load'});await page.locator('main').first().waitFor({state:'visible',timeout:15000});if(name==='builder')await page.getByRole('textbox',{name:'Nazwa projektu'}).waitFor({timeout:15000});else await page.getByRole('heading',{level:1}).first().waitFor({timeout:15000});await page.waitForTimeout(450);const size=await page.evaluate(()=>({viewport:innerWidth,doc:document.documentElement.scrollWidth,body:document.body.scrollWidth,text:document.body.innerText}));await page.screenshot({path:`outputs/mobile/${name}-${width}.png`,fullPage:true});assert.ok(size.doc<=width+1&&size.body<=width+1,`${name} ${width}: horizontal overflow ${JSON.stringify(size)}`);assert.ok(!/SERVICE_UNAVAILABLE|UNAUTHENTICATED|UNKNOWN_ERROR|Ładowanie PLAY/.test(size.text),`${name} ${width}: failed screen ${size.text.slice(0,150)}`);checked++;}
 await context.clearCookies();await page.goto(base+'/play/auth');await page.getByLabel('E-mail',{exact:true}).fill('mobile-a@example.test');await page.getByLabel('Hasło',{exact:true}).fill(password);await page.getByRole('button',{name:'ZALOGUJ I GRAJ'}).click();await page.waitForURL(base+'/play',{timeout:15000});await page.getByRole('link',{name:'ZNAJDŹ GRĘ →'}).waitFor();checked++;await context.close();}
 assert.deepEqual(errors,[],'Browser runtime errors');console.log(`PASS: ${checked} mobile screens and login flows at 375×812, 390×844 and 430×932; no document horizontal overflow.`);
}finally{await browser?.close();if(server)await new Promise(r=>server.close(r));await mf.dispose();}
