import {and,desc,eq,sql} from "drizzle-orm";
import {getDb} from "@/db";
import {courtRedesigns,redesignVotes} from "@/db/play-pilot";
import {courts,users} from "@/db/schema";
import {requireCurrentPlayUser} from "@/lib/play-auth";
import {assertSameOrigin,playError} from "@/lib/play-http";
import {isPlaySport,newId} from "@/lib/play-engine";
import {projectSchema} from "@/lib/project";
export async function GET(request:Request){try{const user=await requireCurrentPlayUser(),db=getDb(),url=new URL(request.url),id=url.searchParams.get("id"),courtId=url.searchParams.get("courtId"),mine=url.searchParams.get("mine")==="1";const rows=await db.select({id:courtRedesigns.id,courtId:courtRedesigns.courtId,title:courtRedesigns.title,sport:courtRedesigns.sport,status:courtRedesigns.status,project:courtRedesigns.project,userId:courtRedesigns.userId,nickname:users.nickname,courtName:courts.name,createdAt:courtRedesigns.createdAt,votes:sql<number>`(SELECT count(*) FROM play_redesign_votes WHERE redesign_id=${courtRedesigns.id})`,supported:sql<number>`EXISTS (SELECT 1 FROM play_redesign_votes WHERE redesign_id=${courtRedesigns.id} AND user_id=${user.id})`}).from(courtRedesigns).innerJoin(users,eq(users.id,courtRedesigns.userId)).innerJoin(courts,eq(courts.id,courtRedesigns.courtId)).where(and(id?eq(courtRedesigns.id,id):undefined,courtId?eq(courtRedesigns.courtId,courtId):undefined,mine?eq(courtRedesigns.userId,user.id):sql`(${courtRedesigns.status}='community' OR (${courtRedesigns.userId}=${user.id} AND ${!!id}))`)).orderBy(desc(courtRedesigns.createdAt)).limit(30);return Response.json({ok:true,projects:rows.map(r=>({...r,project:id||mine?JSON.parse(r.project):undefined,supported:!!r.supported}))},{headers:{"Cache-Control":"no-store"}});}catch(e){return playError(e);}}
export async function POST(request:Request){try{assertSameOrigin(request);const db=getDb(),user=await requireCurrentPlayUser(),body=await request.json();if(body.action==="vote"){const id=String(body.id||""),row=(await db.select().from(courtRedesigns).where(and(eq(courtRedesigns.id,id),eq(courtRedesigns.status,"community"))).limit(1))[0];if(!row)throw new Error("PROJECT_NOT_FOUND");await db.insert(redesignVotes).values({id:newId("vote"),redesignId:id,userId:user.id,createdAt:new Date()}).onConflictDoNothing();return Response.json({ok:true});}
 if(!["publish","save_draft"].includes(body.action))throw new Error("UNKNOWN_ACTION");const courtId=String(body.courtId||""),sport=String(body.sport||"");if(!isPlaySport(sport))throw new Error("INVALID_SPORT");const court=(await db.select().from(courts).where(eq(courts.id,courtId)).limit(1))[0];if(!court)throw new Error("COURT_NOT_FOUND");if(!court.sports.includes(sport))throw new Error("COURT_SPORT_MISMATCH");const p=projectSchema.parse(body.project);if(sport==="basketball"?!p.sport.startsWith("Koszykówka"):!p.sport.startsWith("Piłka nożna")&&p.sport!=="Futsal")throw new Error("PROJECT_SPORT_MISMATCH");const project=JSON.stringify(p);if(new TextEncoder().encode(project).length>500000)throw new Error("PROJECT_TOO_LARGE");const id=`redesign_${user.id}_${p.id}`;const status=body.action==="publish"?"community":"draft";const existing=(await db.select().from(courtRedesigns).where(eq(courtRedesigns.id,id)).limit(1))[0];if(existing&&existing.status==="community")return Response.json({ok:true,id,published:true});await db.insert(courtRedesigns).values({id,courtId,userId:user.id,sport,title:p.name,project,status,createdAt:new Date()}).onConflictDoUpdate({target:courtRedesigns.id,set:{title:p.name,project,status}});return Response.json({ok:true,id,published:status==="community"});}catch(e){return playError(e);}}
