"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type FeedItem={userId:string;nickname:string;sport:string;before:number;after:number;change:number;createdAt:string;gameId:string;scoreA:number;scoreB:number;courtId:string;courtName:string};
type Notification={id:string;type:string;entityId:string|null;title:string;body:string|null;readAt:string|null;createdAt:string};
type Social={followers:number;following:number;feed:FeedItem[];notifications:Notification[];unreadCount:number};

export default function CommunityPage(){
 const [data,setData]=useState<Social|null>(null),[tab,setTab]=useState<"feed"|"notifications">("feed"),[error,setError]=useState("");
 async function load(){const r=await fetch("/api/play/social",{cache:"no-store"});const d=await r.json();if(!r.ok||!d.ok){setError(d.error||"LOAD_FAILED");return;}setData(d);}
 useEffect(()=>{void load();},[]);
 async function markRead(){await fetch("/api/play/social",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"mark_notifications_read"})});await load();}
 if(!data)return <main style={s.center}>{error||"Ładowanie Community…"}</main>;
 return <main style={s.page}>
  <header style={s.header}><Link href="/play" style={s.back}>← PLAY</Link><b>COMMUNITY</b></header>
  <section style={s.hero}><div><div style={s.kicker}>YOUR SPORT NETWORK</div><h1 style={s.h1}>Graj z ludźmi.</h1><p style={s.muted}>Obserwuj graczy, zobacz ich realną aktywność i wróć do gry.</p></div><div style={s.counts}><div><b>{data.following}</b><span>following</span></div><div><b>{data.followers}</b><span>followers</span></div></div></section>
  <div style={s.tabs}><button style={tab==="feed"?s.active:s.tab} onClick={()=>setTab("feed")}>FOLLOWING</button><button style={tab==="notifications"?s.active:s.tab} onClick={()=>setTab("notifications")}>NOTIFICATIONS {data.unreadCount?`(${data.unreadCount})`:""}</button></div>
  {tab==="feed"?<section style={s.stream}>{data.feed.map(item=><article key={`${item.gameId}-${item.userId}`} style={s.item}><div style={s.top}><Link href={`/play/player?nickname=${encodeURIComponent(item.nickname)}&sport=${item.sport}`} style={s.player}>@{item.nickname}</Link><span style={s.time}>{new Date(item.createdAt).toLocaleString("pl-PL")}</span></div><p><b>{item.scoreA}:{item.scoreB}</b> na <Link href={`/play/court?id=${encodeURIComponent(item.courtId)}&sport=${item.sport}`} style={s.link}>{item.courtName}</Link></p><div style={s.elo}><span>{item.before}</span><strong style={{color:item.change>=0?"#77ff55":"#ff7b88"}}>{item.change>=0?"+":""}{item.change}</strong><span>→ {item.after} ELO</span></div><Link href={`/play/game?gameId=${encodeURIComponent(item.gameId)}`} style={s.open}>OPEN GAME →</Link></article>)}{!data.feed.length&&<div style={s.empty}>Obserwuj graczy w Player Discovery, aby ich mecze pojawiały się tutaj.</div>}</section>:<section style={s.stream}><div style={s.readRow}><span>{data.unreadCount} nieprzeczytanych</span>{data.unreadCount>0&&<button style={s.read} onClick={()=>void markRead()}>OZNACZ JAKO PRZECZYTANE</button>}</div>{data.notifications.map(n=><article key={n.id} style={{...s.notice,opacity:n.readAt?.toString()?0.62:1}}><div><b>{n.title}</b><p style={s.muted}>{n.body}</p><span style={s.time}>{new Date(n.createdAt).toLocaleString("pl-PL")}</span></div>{n.type==="challenge_invite"&&n.entityId&&<Link href={`/play/challenge?id=${encodeURIComponent(n.entityId)}`} style={s.open}>OPEN CHALLENGE →</Link>}</article>)}{!data.notifications.length&&<div style={s.empty}>Brak nowych powiadomień.</div>}</section>}
 </main>;
}

const s:Record<string,React.CSSProperties>={page:{minHeight:"100vh",background:"#071016",color:"white",padding:24,fontFamily:"Arial,sans-serif"},center:{minHeight:"100vh",display:"grid",placeItems:"center",background:"#071016",color:"white"},header:{maxWidth:880,margin:"0 auto 24px",display:"flex",justifyContent:"space-between"},back:{color:"#77ff55",textDecoration:"none"},hero:{maxWidth:880,margin:"0 auto 18px",display:"flex",justifyContent:"space-between",gap:20,alignItems:"end"},kicker:{fontSize:11,color:"#77ff55",fontWeight:900,letterSpacing:1.2},h1:{fontSize:"clamp(42px,8vw,78px)",letterSpacing:-3,margin:"6px 0"},muted:{color:"#91a3ad",fontSize:14},counts:{display:"flex",gap:10},tabs:{maxWidth:880,margin:"0 auto 14px",display:"flex",gap:8},tab:{padding:"10px 14px",border:"1px solid #29404a",borderRadius:999,background:"#0d1920",color:"#91a3ad"},active:{padding:"10px 14px",border:"1px solid #77ff55",borderRadius:999,background:"#77ff55",color:"#071016",fontWeight:900},stream:{maxWidth:880,margin:"0 auto",display:"grid",gap:10},item:{border:"1px solid #20343e",borderRadius:18,background:"#0c171e",padding:18},top:{display:"flex",justifyContent:"space-between",gap:10},player:{color:"white",fontWeight:900,textDecoration:"none"},time:{fontSize:11,color:"#758994"},link:{color:"#77ff55",textDecoration:"none"},elo:{display:"flex",gap:8,alignItems:"baseline",fontSize:14},open:{display:"inline-block",marginTop:12,color:"#77ff55",fontWeight:900,fontSize:11,textDecoration:"none"},notice:{border:"1px solid #20343e",borderRadius:16,background:"#0c171e",padding:16,display:"flex",justifyContent:"space-between",gap:14},readRow:{display:"flex",justifyContent:"space-between",alignItems:"center",color:"#91a3ad",fontSize:12},read:{border:0,background:"transparent",color:"#77ff55",fontWeight:900},empty:{padding:22,border:"1px dashed #29404a",borderRadius:16,color:"#91a3ad",textAlign:"center"}};
