"use client";
import {useEffect,useRef} from "react";
import "leaflet/dist/leaflet.css";
export type MapCourt={id:string;name:string;latitude:number;longitude:number;playersNow:number;readyNow:number;isHome:boolean};
export default function CourtMap({courts,sport,position,onSelect}:{courts:MapCourt[];sport:string;position:[number,number]|null;onSelect:(id:string)=>void}){
 const container=useRef<HTMLDivElement>(null),map=useRef<import("leaflet").Map|null>(null),markers=useRef<import("leaflet").LayerGroup|null>(null),select=useRef(onSelect);select.current=onSelect;
 useEffect(()=>{let cancelled=false;void import("leaflet").then(L=>{if(cancelled||!container.current)return;const m=L.map(container.current,{scrollWheelZoom:false}).setView([52.218,21.047],12);map.current=m;L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(m);markers.current=L.layerGroup().addTo(m);m.invalidateSize();});return()=>{cancelled=true;map.current?.remove();map.current=null;markers.current=null;};},[]);
 useEffect(()=>{let cancelled=false;void import("leaflet").then(L=>{if(cancelled||!map.current||!markers.current)return;const group=markers.current;group.clearLayers();for(const c of courts){const box=document.createElement("div"),title=document.createElement("b"),info=document.createElement("p"),link=document.createElement("a");title.textContent=c.name;info.textContent=`${c.playersNow} LIVE · ${c.readyNow} READY`;link.textContent="PLAY HERE →";link.href=`/play/court?id=${encodeURIComponent(c.id)}&sport=${sport}`;box.appendChild(title);box.appendChild(info);box.appendChild(link);L.marker([c.latitude,c.longitude],{icon:L.divIcon({html:`<div class="p-pin${c.isHome?" home":""}"><span>${c.playersNow+c.readyNow || "●"}</span></div>`,className:"",iconSize:[44,44],iconAnchor:[22,44]})}).addTo(group).bindPopup(box).on("click",()=>select.current(c.id));}if(position)L.circleMarker(position,{radius:8,color:"#fff",fillColor:"#54b7ff",fillOpacity:1}).addTo(group).bindTooltip("Twoja lokalizacja");const points=courts.map(c=>[c.latitude,c.longitude] as [number,number]);if(position)points.push(position);if(points.length)map.current.fitBounds(L.latLngBounds(points),{padding:[35,35],maxZoom:15});});return()=>{cancelled=true;};},[courts,position,sport]);
 return <div className="p-map" aria-label="Mapa obiektów sportowych"><div ref={container} style={{height:"100%",width:"100%"}}/></div>;
}
