"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import {ErrorNotice,PlayHeader,Sports,playRequest,when} from "@/components/play-ui";
const initialTime=()=>{const d=new Date(Date.now()+15*60000);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
export default function GamesPage(){const[data,setData]=useState<any>(null),[sport,setSport]=useState("football"),[courtId,setCourtId]=useState(""),[format,setFormat]=useState("3v3"),[startsAt,setStartsAt]=useState(initialTime),[create,setCreate]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const p=new URLSearchParams(location.search);setCreate(p.get("create")==="1");if(p.get("sport"))setSport(p.get("sport")!);if(p.get("courtId"))setCourtId(p.get("courtId")!);},[]);
 const load=useCallback(()=>playRequest("/api/play").then(d=>{setData(d);setError("");}).catch(e=>setError(e.message)),[]);useEffect(()=>{void load();const t=setInterval(()=>{if(document.visibilityState==="visible")void load();},30000);return()=>clearInterval(t);},[load]);
 const courts=data?.courts.filter((c:any)=>c.sports.includes(sport))||[];const selected=courts.some((c:any)=>c.id===courtId)?courtId:courts[0]?.id||"";
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const d=await playRequest("/api/play",{action:"create_game",sport,courtId:selected,format,startsAt:new Date(startsAt).toISOString()});location.assign(`/play/game?gameId=${d.gameId}`);}catch(e){setError((e as Error).message);setBusy(false);}}
 const gameCard=(g:any)=><Link className="p-card" style={{textDecoration:"none",color:"inherit"}} key={g.id} href={`/play/game?gameId=${g.id}`}><div className="p-row"><span className="p-kicker">{g.format}</span><span className="p-badge">{g.status==="completed"?"COMPLETED":`${g.playerCount}/${g.maxPlayers}`}</span></div><h2>{g.courtName}</h2><p className="p-muted">{when(g.startsAt)}</p><span className="p-back">GAME ROOM →</span></Link>;
 return <main className="p-page"><PlayHeader title="GAMES"/><div className="p-row"><div><div className="p-kicker">PLAY NOW</div><h1>Wejdź do gry.</h1></div><button className="p-btn" onClick={()=>setCreate(!create)}>{create?"Zamknij formularz":"CREATE GAME +"}</button></div><Sports sport={sport} setSport={setSport}/><ErrorNotice error={error}/>{create&&<section className="p-card"><h2>Utwórz grę</h2><form className="p-form" onSubmit={submit}><label className="p-field">Boisko<select value={selected} onChange={e=>setCourtId(e.target.value)} required>{courts.map((c:any)=><option value={c.id} key={c.id}>{c.name} · {c.district||c.city}</option>)}</select></label><label className="p-field">Format<select value={format} onChange={e=>setFormat(e.target.value)}>{["1v1","2v2","3v3","5v5"].map(f=><option key={f}>{f}</option>)}</select></label><label className="p-field">Data i godzina<input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)} required/></label><p className="p-muted">Miejsce dla {Number(format[0])*2} graczy. Dołączasz automatycznie jako organizator.</p><button className="p-btn wide" disabled={busy||!selected}>{busy?"Tworzę grę…":"UTWÓRZ GAME ROOM →"}</button></form></section>}
 {data?.myGames.some((g:any)=>g.sport===sport)&&<><h2>Twoje gry</h2><div className="p-grid">{data.myGames.filter((g:any)=>g.sport===sport).slice(0,6).map(gameCard)}</div></>}<h2>Otwarte gry</h2><div className="p-grid">{data?.games.filter((g:any)=>g.sport===sport).map(gameCard)}</div>{data&&!data.games.some((g:any)=>g.sport===sport)&&<p className="p-muted">Brak otwartych gier. Utwórz pierwszą i zaproś graczy.</p>}{!data&&!error&&<p role="status" className="p-muted">Ładowanie gier…</p>}</main>;
}
