"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Submission = { id:string; name:string; city:string; district:string|null; address:string|null; latitude:number; longitude:number; sports:string[]; surface:string|null; lighting:boolean; isFree:boolean; notes:string|null; createdAt:string; submitterNickname:string; submitterEmail:string };

export default function CourtModerationPage(){
 const [items,setItems]=useState<Submission[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState("");
 async function load(){setError("");const r=await fetch("/api/play/courts/moderate",{cache:"no-store"});const d=await r.json();if(!r.ok||!d.ok){setError(d.error||"LOAD_FAILED");return;}setItems(d.submissions||[]);}
 useEffect(()=>{void load();},[]);
 async function act(id:string,action:"approve"|"reject"){setBusy(id);setError("");try{const r=await fetch("/api/play/courts/moderate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({submissionId:id,action})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"REQUEST_FAILED");await load();}catch(e){setError(e instanceof Error?e.message:"REQUEST_FAILED");}finally{setBusy("");}}
 return <main style={s.page}><header style={s.header}><div><div style={s.kicker}>GAMEFIELDS PLAY / ADMIN</div><h1 style={s.h1}>Court moderation.</h1></div><Link href="/play/map" style={s.back}>← MAPA</Link></header>{error&&<div style={s.error}>{error==="FORBIDDEN"?"Brak uprawnień. Ustaw PLAY_ADMIN_EMAILS w środowisku produkcyjnym.":error}</div>}<section style={s.list}>{items.map(x=><article key={x.id} style={s.card}><div style={s.top}><div><div style={s.kicker}>{x.district||x.city}</div><h2 style={s.name}>{x.name}</h2><div style={s.muted}>{x.address||`${x.latitude.toFixed(5)}, ${x.longitude.toFixed(5)}`}</div></div><div style={s.submitter}>@{x.submitterNickname}<small>{x.submitterEmail}</small></div></div><div style={s.meta}><span>{x.sports.join(" / ")}</span><span>{x.surface||"surface n/a"}</span><span>{x.lighting?"lighting":"no lighting"}</span><span>{x.isFree?"free":"paid"}</span></div>{x.notes&&<p style={s.notes}>{x.notes}</p>}<div style={s.actions}><a href={`https://www.openstreetmap.org/?mlat=${x.latitude}&mlon=${x.longitude}#map=18/${x.latitude}/${x.longitude}`} target="_blank" rel="noreferrer" style={s.map}>SPRAWDŹ LOKALIZACJĘ ↗</a><button disabled={busy===x.id} style={s.reject} onClick={()=>void act(x.id,"reject")}>ODRZUĆ</button><button disabled={busy===x.id} style={s.approve} onClick={()=>void act(x.id,"approve")}>OPUBLIKUJ NA MAPIE</button></div></article>)}{!items.length&&!error&&<div style={s.empty}>Brak zgłoszeń oczekujących na moderację.</div>}</section></main>;
}
const s:Record<string,React.CSSProperties>={page:{minHeight:"100vh",background:"#071016",color:"white",padding:"24px 24px 120px",fontFamily:"Arial,sans-serif"},header:{maxWidth:1050,margin:"0 auto 22px",display:"flex",justifyContent:"space-between",gap:18},kicker:{color:"#77ff55",fontSize:10,fontWeight:900,letterSpacing:1.2},h1:{fontSize:"clamp(40px,7vw,70px)",letterSpacing:-4,lineHeight:.9,margin:"8px 0"},back:{color:"#77ff55",textDecoration:"none",fontSize:11,fontWeight:900},error:{maxWidth:1050,margin:"0 auto 14px",padding:12,borderRadius:12,background:"#351519",color:"#ff9da8"},list:{maxWidth:1050,margin:"0 auto",display:"grid",gap:10},card:{padding:18,border:"1px solid #213640",borderRadius:18,background:"#0c171e"},top:{display:"flex",justifyContent:"space-between",gap:18},name:{fontSize:26,margin:"5px 0"},muted:{color:"#91a3ad",fontSize:12},submitter:{display:"grid",justifyItems:"end",fontSize:12,fontWeight:900},meta:{display:"flex",gap:7,flexWrap:"wrap",marginTop:14,color:"#a2b3b9",fontSize:11},notes:{padding:12,borderRadius:10,background:"#0a141a",color:"#c0d0d5",fontSize:13,lineHeight:1.5},actions:{display:"flex",gap:7,flexWrap:"wrap",marginTop:14},map:{padding:"10px 12px",border:"1px solid #31505d",borderRadius:10,color:"#66b8ff",textDecoration:"none",fontSize:10,fontWeight:900},reject:{marginLeft:"auto",padding:"10px 12px",border:"1px solid #703945",borderRadius:10,background:"transparent",color:"#ff9da8",fontWeight:900},approve:{padding:"10px 12px",border:0,borderRadius:10,background:"#77ff55",color:"#071016",fontWeight:950},empty:{padding:24,border:"1px dashed #2b414a",borderRadius:16,color:"#91a3ad"}};
