"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {ErrorNotice,PlayHeader,Sports,playRequest} from "@/components/play-ui";

export default function PlacesPage(){
 const[sport,setSport]=useState("football"),[scope,setScope]=useState<"court"|"district">("court"),[data,setData]=useState<any>(null),[error,setError]=useState("");
 useEffect(()=>{let cancelled=false;setError("");playRequest(`/api/play/place-rankings?sport=${sport}&scope=${scope}`).then(d=>{if(!cancelled)setData(d);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[sport,scope]);
 return <main className="p-page"><PlayHeader title="PLACES" back="/play/more"/><div className="p-stack"><div><div className="p-kicker">COURT VS COURT</div><h1>Najbardziej żywe miejsca wygrywają.</h1><p className="p-muted">Ranking liczy realną aktywność: potwierdzone mecze, różnych graczy i liczbę aktywnych dni w bieżącym miesiącu.</p></div><Sports sport={sport} setSport={setSport}/><div className="p-tabs"><button className={scope==="court"?"p-tab active":"p-tab"} onClick={()=>setScope("court")}>COURTS</button><button className={scope==="district"?"p-tab active":"p-tab"} onClick={()=>setScope("district")}>DISTRICTS</button></div><ErrorNotice error={error}/>{data&&<><section className="p-card"><div className="p-row"><div><div className="p-kicker">{data.city} · {data.season.label}</div><h2>{scope==="court"?"Court Activity Ranking":"District Activity Ranking"}</h2></div><span className="p-badge">LIVE SEASON</span></div><p className="p-muted">10 pkt za mecz · 3 pkt za unikalnego gracza · 5 pkt za aktywny dzień</p></section><section className="p-card"><div className="p-list">{data.ranking.map((r:any)=><div className="p-item" key={r.courtId||r.name}><div style={{minWidth:32,fontWeight:900,fontSize:20}}>#{r.rank}</div><div style={{flex:1}}><b>{r.name}</b><div className="p-muted">{r.district?`${r.district} · `:""}{r.matches} meczów · {r.players} graczy · {r.activeDays} dni</div></div><span className="p-badge">{r.score} PTS</span></div>)}</div>{data.ranking.length===0&&<p className="p-muted">Brak potwierdzonych meczów w tym miesiącu. Pierwszy rozegrany mecz uruchomi ranking miejsca.</p>}</section></>}</div></main>;
}
