"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import CourtMap,{MapCourt} from "@/components/play/court-map";
import {ErrorNotice,PlayHeader,Sports,playRequest,when} from "@/components/play-ui";
import {distanceKm} from "@/lib/play-courts";
type Court=MapCourt & {city:string;district:string|null;surface:string|null;lighting:boolean;isFree:boolean;problemCount:number;openGames:any[];events:any[];rank?:number;score?:number;matches?:number;players?:number;activeDays?:number;trend?:"up"|"down"|"flat"|"new";rankDelta?:number|null};
export default function MapPage(){
 const[sport,setSport]=useState("football"),[data,setData]=useState<any>(null),[places,setPlaces]=useState<any>(null),[error,setError]=useState(""),[filter,setFilter]=useState("all"),[free,setFree]=useState(false),[lighting,setLighting]=useState(false),[surface,setSurface]=useState(""),[district,setDistrict]=useState(""),[position,setPosition]=useState<[number,number]|null>(null),[geoBusy,setGeoBusy]=useState(false),[selected,setSelected]=useState("");
 useEffect(()=>{const p=new URLSearchParams(location.search);if(p.get("sport"))setSport(p.get("sport")!);if(p.get("filter"))setFilter(p.get("filter")!);},[]);
 const load=useCallback(async()=>{try{const[d,p]=await Promise.all([playRequest(`/api/play/discovery?sport=${sport}`),playRequest(`/api/play/place-rankings?sport=${sport}&scope=court`)]);setData(d);setPlaces(p);setError("");}catch(e){setError((e as Error).message);}},[sport]);
 useEffect(()=>{void load();const t=setInterval(()=>{if(document.visibilityState==="visible")void load();},30000);return()=>clearInterval(t);},[load]);
 const rankingByCourt=useMemo(()=>new Map((places?.ranking||[]).map((r:any)=>[r.courtId,r])),[places]);
 const enriched=useMemo(()=>((data?.courts||[]).map((c:Court)=>Object.assign({},c,rankingByCourt.get(c.id)||{}))),[data,rankingByCourt]);
 const courts: Court[]=useMemo(()=>{let rows=enriched.filter((c:Court)=>(!free||c.isFree)&&(!lighting||c.lighting)&&(!surface||c.surface===surface)&&(!district||c.district===district)&&(filter!=="play"||c.playersNow+c.readyNow>0||c.openGames.some(g=>new Date(g.startsAt).getTime()<Date.now()+7200000))&&(filter!=="ready"||c.readyNow>0)&&(filter!=="game"||c.openGames.some(g=>g.playerCount<g.maxPlayers))&&(filter!=="improve"||c.problemCount>0)&&(filter!=="event"||c.events.length>0));if(position)rows=[...rows].sort((a:Court,b:Court)=>distanceKm({latitude:position[0],longitude:position[1]},a)-distanceKm({latitude:position[0],longitude:position[1]},b));return rows;},[enriched,filter,free,lighting,surface,district,position]);
 function locate(){if(!navigator.geolocation){setError("SERVICE_UNAVAILABLE");return;}setGeoBusy(true);navigator.geolocation.getCurrentPosition(p=>{setPosition([p.coords.latitude,p.coords.longitude]);setGeoBusy(false);},()=>{setError("LOCATION_UNAVAILABLE");setGeoBusy(false);},{enableHighAccuracy:false,timeout:10000,maximumAge:60000});}
 const today=(value:string)=>{const d=new Date(value),n=new Date();return d.getFullYear()===n.getFullYear()&&d.getMonth()===n.getMonth()&&d.getDate()===n.getDate();};
 const trendLabel=(c:Court)=>c.trend==="up"?`↑${c.rankDelta||1}`:c.trend==="down"?`↓${Math.abs(c.rankDelta||1)}`:c.trend==="new"?"NEW":"→";
 return <main className="p-page"><PlayHeader title="MAP / LIVE DISCOVERY"/><div className="p-row"><div><div className="p-kicker">FIND IT. PLAY IT.</div><h1>Gra jest w mieście.</h1></div><Link className="p-btn secondary" href="/play/courts/add">ADD A SPOT +</Link></div><Sports sport={sport} setSport={setSport}/><div className="p-tabs">{[["all","WSZYSTKIE"],["play","PLAY NOW"],["ready","READY"],["game","OPEN GAME"],["event","EVENTS"],["improve","IMPROVE"]].map(([value,label])=><button key={value} aria-pressed={filter===value} className={filter===value?"p-tab active":"p-tab"} onClick={()=>setFilter(value)}>{label}</button>)}</div>
 <div className="p-row" style={{marginBottom:16}}><div className="p-tabs" style={{margin:0}}><button className={free?"p-tab active":"p-tab"} aria-pressed={free} onClick={()=>setFree(!free)}>FREE</button><button className={lighting?"p-tab active":"p-tab"} aria-pressed={lighting} onClick={()=>setLighting(!lighting)}>OŚWIETLENIE</button></div><button className="p-btn secondary" disabled={geoBusy} onClick={locate}>{geoBusy?"Ustalam lokalizację…":position?"Odśwież moją lokalizację":"Najbliżej mnie (opcjonalnie)"}</button></div>
 <div className="p-grid" style={{marginTop:0}}><label className="p-field">Dzielnica<select value={district} onChange={e=>setDistrict(e.target.value)}><option value="">Wszystkie dzielnice</option>{Array.from(new Set<string>((data?.courts||[]).map((c:Court)=>c.district).filter(Boolean))).map(d=><option key={d}>{d}</option>)}</select></label><label className="p-field">Nawierzchnia<select value={surface} onChange={e=>setSurface(e.target.value)}><option value="">Wszystkie nawierzchnie</option>{Array.from(new Set<string>((data?.courts||[]).map((c:Court)=>c.surface).filter(Boolean))).map(s=><option key={s}>{s}</option>)}</select></label></div><ErrorNotice error={error}/><CourtMap courts={courts} sport={sport} position={position} onSelect={setSelected}/><p className="p-muted">{courts.length} obiektów · ranking aktywności: mecze + gracze + regularność · LIVE + READY odświeżane automatycznie</p>
 {!data&&!error&&<p className="p-muted" role="status">Ładowanie obiektów…</p>}<section className="p-grid">{courts.map(c=>{const gamesToday=c.openGames.filter(g=>today(g.startsAt)).length;return <article className="p-card" key={c.id} style={selected===c.id?{borderColor:"#77ff55"}:undefined}><div className="p-row"><span className="p-kicker">{c.district||c.city}</span><div className="p-row">{c.rank&&<span className="p-badge">#{c.rank} COURT · {trendLabel(c)}</span>}{c.isHome&&<span className="p-badge">HOME COURT</span>}</div></div><h2>{c.name}</h2><div className="p-stats"><div><b>{c.playersNow+c.readyNow}</b><span>LIVE + READY</span></div><div><b>{gamesToday}</b><span>gry dziś</span></div><div><b>{c.score||0}</b><span>activity pts</span></div></div><p className="p-muted">{c.matches||0} meczów w tym miesiącu · {c.players||0} graczy · {c.activeDays||0} aktywnych dni{position?` · ${distanceKm({latitude:position[0],longitude:position[1]},c).toFixed(1)} km`:""}</p><p className="p-muted">{c.isFree?"FREE":"PAID"} · {c.surface||"Nawierzchnia do weryfikacji"}{c.lighting?" · Oświetlenie":""}{c.problemCount?` · ${c.problemCount} zgłoszeń problemu`:""}</p>{c.openGames.slice(0,2).map(g=><Link key={g.id} className="p-item" href={`/play/game?gameId=${g.id}`}><div><b>{g.format} · {g.playerCount}/{g.maxPlayers}</b><div className="p-muted">{when(g.startsAt)}</div></div><span className="p-back">GAME →</span></Link>)}{c.events.map(e=><Link className="p-item" key={e.id} href={`/play/tournaments?id=${e.id}`}><div><b>{e.name}</b><div className="p-muted">{when(e.startsAt)}</div></div><span className="p-badge">EVENT</span></Link>)}<Link className="p-btn secondary wide" href={`/play/court?id=${c.id}&sport=${sport}`}>PLAY HERE →</Link></article>})}</section>{data&&!courts.length&&<section className="p-card"><h2>Jeszcze spokojnie.</h2><p className="p-muted">Zmień filtry albo zaproś graczy na swoje boisko.</p><button className="p-btn secondary" onClick={()=>{setFilter("all");setFree(false);setLighting(false);setSurface("");setDistrict("");}}>Pokaż wszystkie obiekty</button></section>}</main>;
}
